codecleanup: remove php warning from ticketchange method
lmsgit/lms pull request #1877
Opened 2020-12-08 15:57 UTC by interduo

2020-12-08 16:04 UTC, chilek commented
Jakie etykiety?

2020-12-08 16:05 UTC, interduo commented
Szukałem właśnie czy to też ma lecieć do stable.

2020-12-28 19:23 UTC, chilek requested changes
Moim zdaniem to już jest poprawione w master. Mylę się?

2020-12-29 12:44 UTC, interduo commented
Tak - jest już poprawione.

2020-12-29 12:44 UTC, closed without merging