codecleanup: use html entity instead tripple dots
lmsgit/lms pull request #1943
Opened 2021-01-29 16:13 UTC by interduo

2021-01-29 16:43 UTC, chilek requested changes

2021-01-29 16:43 UTC, chilek commented on templates/default/user/usergroupassignments.html
>  					</option>
przy wszystkich występieniach username i rusername dla użytkownika od razu proponuję |escape dać na końcu.

2021-01-29 16:43 UTC, chilek commented on templates/default/voipaccount/voipaccountbillinglist.html
>  						{/foreach}
tu też |escape pewnie.

2021-01-29 16:43 UTC, chilek commented on templates/default/voipaccount/voipaccountlist.html
>                  </a>
i tu

2021-01-29 16:43 UTC, merged

2021-01-29 16:44 UTC, chilek commented
Jednak |escape robić lepiej oddzielnymi commitami - łatwiej potem przenieść do stableów.

2021-01-29 16:44 UTC, chilek commented
10q

2021-01-29 17:37 UTC, interduo commented
@awbnet masz to co chciałeś ale globalnie a nie tylko na liście vlanów ;)

2021-02-02 21:39 UTC, chilek commented
Zamiana "..." na `&hellip;` narobiła całą masą problemów z |truncate:.......|escape :(