enhancement: allow to store mac address in net device (LMS+ #1591)
lmsgit/lms pull request #1962
Opened 2021-02-17 10:18 UTC by rafalpietraszewicz

2021-02-17 11:39 UTC, interduo commented
A jeśli urządzenie sieciowe ma wiele adresów mac?

2021-02-17 11:43 UTC, chilek commented
> A jeśli urządzenie sieciowe ma wiele adresów mac? Prosty przykład ... routery klienckie i adresy MAC na portach WAN/LAN.

Tu raczej chodzi o główny MAC podawany na pudełku na potrzeby magazynowe. Wątpię, żeby produdent na pudełku podawał np. 20 MAC-ów?

2021-02-17 11:44 UTC, interduo commented
Właśnie podaje dwa LAN i WAN.

2021-02-17 11:44 UTC, chilek commented on lib/LMSManagers/LMSNetDevManager.php
> +    {
exclude czy exlude?
Czy na pewno tu wartość excludeid trafi bez SQL injection?

2021-02-17 11:45 UTC, chilek commented on lib/LMSManagers/LMSNetDevManager.php
> +        return ($netdev ? true : false);
Można po prostu:
```php
return !empty($netdev);
```

2021-02-17 11:45 UTC, chilek commented on lib/locale/pl_PL/strings.php
> +$_LANG['MAC address already exists!'] = 'Adres Mac już istnieje!';
Jest uzasadnienie dla `Mac` pisanego dużą literą?

2021-02-17 12:13 UTC, rafalpietraszewicz commented
> Właśnie podaje dwa LAN i WAN.

Zrobię poprawkę, która pozwoli przechowywać dowolną ilość różnych typów mac.

2021-02-17 12:16 UTC, chilek commented
Tak jak rozmawialiśmy - najlepiej z etykietami tekstowymi w postaci combobox.

2021-02-17 12:33 UTC, rafalpietraszewicz commented on lib/LMSManagers/LMSNetDevManager.php
> +    {
w momencie wywołania metody jest podawane intval(), ale dla pewności jeszcze zrobię intval() w metodzie.

2021-02-25 10:07 UTC, rafalpietraszewicz commented
Do zarządzania urządzeniem sieciowym został dodany panel 'Adresy Mac'. Panel pozwala na zarządzanie adresami mac nadanymi przez producenta urządzenia. 

![Zrzut ekranu z 2021-02-25 11-02-00](https://user-images.githubusercontent.com/7595420/109137168-32064b00-7759-11eb-862d-ef7755f2b665.png)

Można przechowywać wiele adresów mac. Tylko jeden z nich może być 'główny'. Jeśli mac jest oznaczony jako 'główny' to będzie on automatycznie podpowiadany jako mac podczas dodawania adresów IP i to jest właściwie jak na razie jedyne zastosowanie flagi 'główny' dla mac.

2021-02-25 11:18 UTC, chilek requested changes

2021-02-25 11:18 UTC, chilek commented on templates/default/netdev/netdevmacs.html
>  				<input type="checkbox" form="netdevmacadd" name="main" id="mac-main" class="mac-edit-field"
Poproszę o `Main' => 'Primary. Wystarczy w UI.

2021-02-25 11:18 UTC, chilek commented on js/templates/netdev/netdevmacs.js
> +
Poprawka niekonieczna, ale warto zdawać sobie sprawę w przyszłości - lepiej od razu cały kod HTML przygotować i od razu go jednym wywołaniem wstawić niż robić to na raty poprzez tak naprawdę DOM - to jest po prostu wolniejsze.

2021-02-25 11:18 UTC, chilek commented on js/templates/netdev/netdevmacs.js
> +
Cały select lepiej było zbudować jako kod HTML, a potem wstawić od razu całość do DOMu.

2021-02-25 11:18 UTC, chilek commented on lib/LMSManagers/LMSNetDevManager.php
> +            }
netdev mac to powinien być oddzielny zasób SYSLOG.

2021-02-25 11:18 UTC, chilek commented on lib/locale/pl_PL/strings.php
> +$_LANG['Main mac address already exists!'] = 'Główny adres mac już istnieje!';
Tu też może MAC dużymi?

2021-02-25 11:18 UTC, chilek commented on modules/netdevmac.php
> +$error = [];
Ja wiem, że już wymagamy PHP 7.1, ale czy nie lepiej jednak użyć tu array();?

2021-02-25 11:18 UTC, chilek commented on modules/netdevmac.php
> +            $mac = (!empty($params['mac']) ? Utils::removeInsecureHtml($params['mac']) : null);
MAC  lepiej sprawdzić preg_matchem. Nie wiem czy nie mamy gotowej funkcji check_mac().

2021-02-25 12:46 UTC, merged